# -*- coding: utf-8 -*-
"""walmart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fkybt_2MSLqmbiPsDHesW_QDh_xwHyIU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import duckdb

from google.colab import files

uploaded = files.upload()

!unzip Walmart_SQL_Python-main.zip

df = pd.read_csv("Walmart_SQL_Python-main/Walmart.csv")

df.head()

df.info()

df.isnull().sum()

df=df.dropna().copy()

df.isnull().sum()

df["date"] = pd.to_datetime(df["date"])
df.dtypes

df["unit_price"].head()

df["unit_price"] = df["unit_price"].replace(r'[\$,]', '', regex=True)

df["unit_price"] = pd.to_numeric(df["unit_price"])

df.dtypes

df["total_amount"] = df["unit_price"] * df["quantity"]

df.head()

con = duckdb.connect()
con.register("walmart", df)

con .sql("""
SELECT *
FROM walmart
LIMIT 5;
""").df()

con.sql("""
SELECT COUNT(*) AS total_transactions
FROM walmart;
""").df()

con.sql("""
SELECT ROUND(SUM(total_amount), 2) AS total_sales
FROM walmart;
""").df()

con.sql("""
SELECT
    City,
    ROUND(SUM(total_amount), 2) AS total_sales
FROM walmart
GROUP BY City
ORDER BY total_sales DESC
LIMIT 5;
""").df()

con.sql("""
SELECT
    payment_method,
    COUNT(*) AS total_transactions
FROM walmart
GROUP BY payment_method
ORDER BY total_transactions DESC;
""").df()

con.sql("""
SELECT
    category,
    ROUND(SUM(total_amount), 2) AS total_sales
FROM walmart
GROUP BY category
ORDER BY total_sales DESC;
""").df()

con.sql("""
SELECT
    Branch,
    ROUND(SUM(total_amount), 2) AS total_sales
FROM walmart
GROUP BY Branch
ORDER BY total_sales DESC;
""").df()

con.sql("""
SELECT
    category,
    ROUND(AVG(rating), 2) AS average_rating
FROM walmart
GROUP BY category
ORDER BY average_rating DESC;
""").df()

con.sql("""
SELECT
    strftime(date, '%Y-%m') AS month,
    ROUND(SUM(total_amount), 2) AS total_sales
FROM walmart
GROUP BY month
ORDER BY month;
""").df()

city_sales = con.sql("""
SELECT
    City,
    ROUND(SUM(total_amount),2) AS total_sales
FROM walmart
GROUP BY City
ORDER BY total_sales DESC
LIMIT 10;
""").df()

city_sales

plt.figure(figsize=(10,5))
plt.bar(city_sales["City"], city_sales["total_sales"])
plt.title("Top 10 Cities by Sales")
plt.xlabel("City")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.show()

category_sales = con.sql("""
SELECT
    category,
    ROUND(SUM(total_amount),2) AS total_sales
FROM walmart
GROUP BY category
ORDER BY total_sales DESC;
""").df()

category_sales

plt.figure(figsize=(8,5))
plt.bar(category_sales["category"], category_sales["total_sales"])
plt.title("Sales by Product Category")
plt.xlabel("Category")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.show()

payment = con.sql("""
SELECT
    payment_method,
    COUNT(*) AS total
FROM walmart
GROUP BY payment_method;
""").df()

payment

plt.figure(figsize=(6,6))
plt.pie(payment["total"],
        labels=payment["payment_method"],
        autopct="%1.1f%%")
plt.title("Payment Method Distribution")
plt.show()

monthly_sales = con.sql("""
SELECT
    strftime(date,'%Y-%m') AS month,
    ROUND(SUM(total_amount),2) AS total_sales
FROM walmart
GROUP BY month
ORDER BY month;
""").df()

monthly_sales

plt.figure(figsize=(10,5))
plt.plot(monthly_sales["month"],
         monthly_sales["total_sales"],
         marker="o")

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.grid(True)

plt.show()